### PR TITLE
README.md - Populate the readme with appropriate content

### LINKED ISSUE #2: Please add README description + install instructions + screenshots
Also add the freecad forum announcement thread: https://forum.freecadweb.org/viewtopic.php?t=12559

### PR DESCRIPTION
**Pull request by luzpaz**
Closes #2

### CODE REVIEW

**Comment by luzpaz** [comment]
Preview PR: https://github.com/luzpaz/FreeCAD-Timber/blob/README-tweek/README.md

**Comment by j-wiedemann** [comment]
HI luzpaz ! Thanks for this PR. I've not seen it before. The PR look in conflict and I'm not able to resolve conflicts... Do you want to remake the PR ? or I will add it manually

**Comment by luzpaz** [comment]
No worries, I'll take a look at it and see if I can rebase it

**Comment by luzpaz** [comment]
@wood-galaxy incorporated your recent README update and rebased. Please preview https://github.com/luzpaz/FreeCAD-Timber/blob/README-tweek/README.md

Do you mind adding some content in the Usage section so people would understand how it worked?

**Pull request merged**
